import orjson
import pathlib
import csv
from datetime import datetime

# Path to the output file generated by openalex.py
OUT = pathlib.Path("data/raw_openalex.jsonl")
CSV_OUT = pathlib.Path("data/openalex_sample.csv")

N = 5  # Number of records to process

fields = [
    "authorships",
    "display_name",  # title
    "abstract_inverted_index",
    "publication_date",
    "related_works"
]

rows = []

with open(OUT, "rb") as f:
    for i, line in enumerate(f):
        if i >= N:
            break
        record = orjson.loads(line)
        row = {}
        # authorships as string (list of dicts)
        row["authorships"] = orjson.dumps(record.get("authorships", [])).decode()
        # title
        row["title"] = record.get("display_name", "")
        # abstract_inverted_index as string
        row["abstract_inverted_index"] = orjson.dumps(record.get("abstract_inverted_index", {})).decode()
        # publication_date as yyyy-mm-dd
        pub_date = record.get("publication_date", "")
        try:
            row["publication_date"] = datetime.strptime(pub_date, "%Y-%m-%d").strftime("%Y-%m-%d")
        except Exception:
            row["publication_date"] = pub_date
        # related_works as string (list)
        row["related_works"] = orjson.dumps(record.get("related_works", [])).decode()
        rows.append(row)

with open(CSV_OUT, "w", newline="") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=["authorships", "title", "abstract_inverted_index", "publication_date", "related_works"])
    writer.writeheader()
    for row in rows:
        writer.writerow(row)

print(f"Saved {N} records to {CSV_OUT}")
