import orjson
import pathlib

# Path to the output file generated by openalex.py
OUT = pathlib.Path("data/raw_openalex.jsonl")

# Read and parse the first N records to inspect the fields
N = 5  # Number of records to preview

fields = set()
examples = []

with open(OUT, "rb") as f:
    for i, line in enumerate(f):
        if i >= N:
            break
        record = orjson.loads(line)
        examples.append(record)
        fields.update(record.keys())

print(f"Found {len(fields)} unique fields in the first {N} records:")
for field in sorted(fields):
    print(f"- {field}")

print("\nExample record:")
import pprint
pprint.pprint(examples[0])
